import time
t=0.1
'''
cache = "大家好 ~_~ 我是熊张洋，来自湖北黄石。"
print("%s"%cache)
time.sleep(t*(len(cache)))
cache = "目前是武汉大学计算机学院的一枚研究生"
print("%s"%cache)
time.sleep(t*(len(cache)))
cache = "兴趣爱好："
print("%s"%cache,end="")
time.sleep(t*(len(cache)))
cache = "运动、听音乐、寻找美食"
print("%s"%cache)
time.sleep(t*(len(cache)))
cache = "大学毕业之后，通过校招顺利进入到深圳的一家公司"
print("%s"%cache)
time.sleep(t*(len(cache)))
cache = "在工作当中接触到了各式各样的工作伙伴，学到了许多宝贵的知识；也发现了新的人生目标。"
print("%s"%cache)
time.sleep(t*(len(cache)))
cache = "目前是武汉大学计算机学院的一枚研究生"
print("%s"%cache)
time.sleep(t*(len(cache)))
...'''


z="大家好！~_~ 我是熊张洋，湖北黄石人。"
for i in range (len(z)):
    print("%s"%z[i],end="")
    time.sleep(0.3)
print()
z="身高：178.5CM, 体重75KG。"
for i in range (len(z)):
    print("%s"%z[i],end="")
    time.sleep(0.3)
print()
z="目前是武汉大学计算机学院的一枚研究生。"
for i in range (len(z)):
    print("%s"%z[i],end="")
    time.sleep(0.3)
print()
z="兴趣爱好：打篮球、跑步、听音乐、寻找美食。"
for i in range (len(z)):
    print("%s"%z[i],end="")
    time.sleep(0.3)
print()
z=". . . . . . . . . . . . . . . . . . "
for i in range (len(z)):
    print("%s"%z[i],end="")
    time.sleep(0.3)

'''
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
'''